name: nova
summary: Cloud computing fabric controller
description: OpenStack's Compute module
vendor: OpenStack <openstack-dev@lists.openstack.org>
version: 12.0.0
icon: icon.svg

parts:
  python3:
    requirements: requirements.txt 
    stage-packages: [libxml2-dev, libxslt1-dev]
  nova:
    type: python3-project
    after: [python3]
    source: .

binaries:
  - name: nova-idmapshift
  - name: nova-api
  - name: nova-xvpvncproxy
  - name: nova-api-metadata
  - name: nova-all
  - name: nova-compute
  - name: nova-console
  - name: nova-network
  - name: nova-api-ec2
  - name: nova-rootwrap-daemon
  - name: nova-serialproxy
  - name: nova-api-os-compute
  - name: nova-spicehtml5proxy
  - name: nova-consoleauth
  - name: nova-dhcpbridge
  - name: nova-cells
  - name: nova-conductor
  - name: nova-scheduler
  - name: nova-novncproxy
  - name: nova-objectstore
  - name: nova-cert
  - name: nova-manage
  - name: nova-rootwrap

